### ISSUE TITLE
Wrong NPM installation command

### ISSUE THREAD

**Issue by ScarletFlash** [bpmn-io/bpmn-js-guideline-validation#2]
Readme command `npm install bpmn-js-guideline-validation` doesn't work, because package is published as **bpmn-js-guideline-validator**.

So, the correct command is `npm install bpmn-js-guideline-validator`.

**Comment by pinussilvestrus** [comment]
Hi @ScarletFlash , thanks for reporting.

We are open for contributions which 
* Updating the `README` docs with the correct package (we would, I guess, update the repository name afterwards), or
* Updating the `package` name (we would update the package on `npm` registry then)

**Comment by pinussilvestrus** [comment]
@ScarletFlash, instead of using this project, I can also really recommend using https://github.com/bpmn-io/bpmn-js-bpmnlint
